BUILD:
  DATALOADER:
    CHOICE: "Szada"
  LOSS:
    CHOICE: "BCEWithLogitsLoss"
    REDUCTION: "mean"
    USE_POS_WEIGHT: True
    POS_WEIGHT: 4.0
  MODEL:
    CHOICE: "Siamese_unet_diff"
    IN_CHANNEL: 3
    OUT_CHANNEL: 2
  OPTIMIZER:
    CHOICE: "SGD"
  LR_SCHEDULER:
    CHOICE: "WarmupCosineLR"
  USE_CHECKPOINT: True
  USE_TENSORBOARD: True
  TEST_WHEN_TRAIN: True
  
CHECKPOINT:
  PATH: "checkpoint/"
  PERIOD: 500
  
DATASETS:
  TRAIN_CSV: "data/Szada/train.csv"
  TEST_CSV: "data/Szada/test.csv"

DATALOADER:
  NUM_WORKERS: 0
  BATCH_SIZE: 32
  TEST_BATCH_SIZE: 1
  SHUFFLE: True
  TEST_SHUFFLE: False
  
EVAL:
  METRIC: ["Pr","Re","F1","PCC","Kappa"]
  INITIAL_METRIC: [0.6,0.6,0.6,0.9,0.6]
  CHECKPOINTS_PATH: "checkpoint/"
  SAVE_PATH: "logs/"
  SAVE_NAME: "eval.csv"

MODEL:
  DEVICE: "cuda"
  
SOLVER:
  BASE_LR: 0.001
  NUM_EPOCH: 2000
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0
  TEST_PERIOD: 11
  TEST_BETTER_SAVE: True
  
  LR_SCHEDULER:
    MAX_ITERS: 20
    LAST_EPOCH: -1
    WARMUP_FACTOR: 0.05
    WARMUP_ITERS: 20
    WARMUP_METHOD: "linear"
    
TENSORBOARD:
  ID: ""
  PATH: "logs/tensorboard/"